### ISSUE TITLE
The --gen-tune option returns the wrong BEST_FLAGS result

### ISSUE THREAD

**Issue by guillon** [antmox/xplfl#2]
When tuning for instance with the xplfl command the BEST_FLAGS output does not give the right result:
```
> xplfl.py -f flags_min.txt -r ./build_size.sh   -j 64 --gen-tune="-flto -Ofast"
XRES 1994 RUN-1535704346124076 -Ofast
XRES 1100 RUN-1535704346124736 -flto -Ofast
XRES 2190 RUN-1535704346856916 -flto
XRES 1108 RUN-1535704346857497 -flto -Oz
BEST_FLAGS -flto -Oz
```

Obviously the output is wrong: the best flags are `-flto -Ofast` (1100), not `-flto -Oz` (1108).

Note also that while it seems from the documentation that --gen-tune is supposed to tune the input flags, in this example, the `-Oz` flag is added while it is not from the original flags, the logic seems broken, isn't it?

Here is the flags_min.txt file:
```
-flto
-Oz
-Ofast
```

**Comment by antmox** [comment]
thanks dude! it should be fixed now :)
